name: Build Retro Video Games Portal

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Build backend (if applicable)
        working-directory: ./server
        run: |
          if [ -f package.json ] && grep -q 'build' package.json; then npm run build; else echo "No build script"; fi

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: |
          if [ -f package.json ] && grep -q 'build' package.json; then npm run build; else echo "No build script"; fi 